-- ============================================================================
-- A booking reference the desk can say out loud.
--
-- `bookings.id` is a uuid and stays the primary key - every foreign thing that
-- points at a booking (the panel's update, its delete, its export) addresses it
-- by that, and it is not worth rewriting for cosmetics. But a uuid is unusable
-- as a *reference*: nobody reads `9f3c1a7e-2b44-...` down a phone, and printed
-- in a spreadsheet column it is noise the owner scrolls past.
--
-- So the booking gets a second identity, and it is the one people use:
--
--     RMG-001, RMG-002, RMG-003, ...
--
-- Unique, never reused, and generated by the database so two requests arriving
-- in the same second cannot be handed the same one. It travels with the booking
-- everywhere it goes - the guest's WhatsApp message, the desk's email, the
-- spreadsheet row and the Bookings tab - so all four are talking about one
-- thing and the desk can match them without reading a date and a name.
--
-- Gaps are expected and are not a fault. A sequence is not rolled back, so a
-- reference reserved for a guest who then closed the tab is simply spent. The
-- number is a name, not a count of bookings - the count is `select count(*)`.
-- ============================================================================

create sequence public.booking_reference_seq start with 1;

/**
 * The next reference, zero padded to three digits and widening on its own.
 *
 * `lpad` only ever adds, so RMG-001 through RMG-999 are three digits and the
 * thousandth is RMG-1000 without anybody migrating anything. Sorting a text
 * column puts RMG-1000 before RMG-999, which is why the panel keeps ordering by
 * `created_at` and not by this.
 */
create or replace function public.next_booking_reference()
returns text
language sql
volatile
as $$
  select 'RMG-' || lpad(nextval('public.booking_reference_seq')::text, 3, '0')
$$;

-- The default is volatile, so Postgres rewrites the table and calls it once per
-- row: every booking already recorded gets its own reference, which is what
-- makes the column `not null unique` from the start. The order it hands them
-- out in during that rewrite is not defined, so an old booking's number says
-- nothing about when it arrived - only bookings taken from here on run in
-- order. `created_at` is what the panel sorts by either way.
alter table public.bookings
  add column reference text not null unique default public.next_booking_reference();

comment on column public.bookings.reference is
  'Human reference (RMG-001). Unique. Quoted in WhatsApp, the email and the sheet.';

-- Same rule as every table here: `anon` is the key in the browser bundle and is
-- granted nothing. The reference is reserved through the `intake` edge function,
-- which holds the service_role key - never by the page itself. A function left
-- executable by PUBLIC would let anyone burn through the sequence from a script.
revoke all on function public.next_booking_reference() from public, anon, authenticated;
revoke all on sequence public.booking_reference_seq from public, anon, authenticated;

-- The one caller. It needs both: `execute` to reserve a reference before the
-- guest leaves for WhatsApp, and `usage` because the column default calls
-- `nextval` as whoever is doing the insert.
grant execute on function public.next_booking_reference() to service_role;
grant usage on sequence public.booking_reference_seq to service_role;
